# -*- coding: utf-8 -*-
"""CS19ProRankings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aeibTJzDRmkmO84LhuzpwF4oXL09sTgR
"""

import random
import json
import urllib.request

# possibly need matplotlib (for plotting the points obviously lol)
# possible ideas for graphing: circle dot plot with darker colors for more hours played, distance from center is ranking
# look into principal component analysis and dimensionality reduction, SCIKIT

def build_csgo_url(api_key, player_id):
  baseurl = "http://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v0002/"
  csgo_appid = 730
  
  params = {
      "appid" : csgo_appid,
      "key" : api_key,
      "steamid" : player_id
  }

  url = baseurl + "?" + urllib.parse.urlencode(params)
  return url

# print(build_csgo_url("3D7DE697F2F2B5A7DB89B1AF65F5830C", "76561198068252994"))

class player_point:
  # planned members
  # ranking, heat (hours played), location on plot (generated by random)
  # planned functions
  # add_to_plot, generate_location